# Permalinks
permalink:        pretty
encoding: UTF-8

# Setup
title:               OpenDreamKit
tagline:             'Open Digital Research Environment Toolkit for the Advancement of Mathematics'
description:         'A project funded by the <a href="https://ec.europa.eu/programmes/horizon2020/">Horizon 2020</a> - <a href="https://ec.europa.eu/programmes/horizon2020/en/h2020-section/european-research-infrastructures-including-e-infrastructures">European Research Infrastructures</a> Work Programme'
url:                 http://opendreamkit.org
baseurl:             ''
paginate:            18
paginate_path:       "/news/page:num/"
blog_path:           "/news/"
future:              True
plugins:
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-redirect-from

exclude: ['_tagpages/README.md', '*.synctex.gz', '*.aux', '*.nav', '*.out', '*.snm', '*.tex', '*.log', '*.toc', 'vendor']


# About/contact
author:
  name:              'The OpenDreamKit consortium'
  url:               http://opendreamkit.org
  email:             contact@opendreamkit.org
  twitter:           opendreamkit

repository:          OpenDreamKit/OpenDreamKit.github.io

collections:
    tagpages:
        output: true
        permalink: /tag/:path

# Custom vars
version:             0.3.0
repository:          OpenDreamKit/OpenDreamKit.github.io
bootstrap:           bootstrap-custom
tagfolder:           tag
menu:
    - title: 'About'
      link: '/about/'
    - title: 'Project'
      slug: 'project'
    - title: 'People'
      slug: 'people'
    - title: 'Use cases'
      link: '/tag/use-case'
    - title: 'Try'
      link: '/try'
    - title: 'Events'
      slug: 'events'
    - title: 'Values'
      slug: 'values'
    - title: 'Blog'
      link: '/tag/blogpost'
