# Permalinks
permalink:        pretty

# Setup
title:               OpenDreamKit
tagline:             'Open Digital Research Environment Toolkit for the Advancement of Mathematics'
description:         'A project funded by the <a href="https://ec.europa.eu/programmes/horizon2020/">Horizon 2020</a> - <a href="https://ec.europa.eu/programmes/horizon2020/en/h2020-section/european-research-infrastructures-including-e-infrastructures">European Research Infrastructures</a> Work Programme'
url:                 http://opendreamkit.org
baseurl:             ''
paginate:            10
paginate_path:       "/news/page:num/"
blog_path:           "/news/"
future:              True
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-redirect-from

exclude: ['public/*.md', 'public/*.html', 'tag/README.md', '*.synctex.gz', '*.aux', '*.nav', '*.out', '*.snm', '*.tex', '*.log', '*.toc']


# About/contact
author:
  name:              'The OpenDreamKit consortium'
  url:               http://opendreamkit.org
  email:             contact@opendreamkit.org
  twitter:           opendreamkit

repository:          OpenDreamKit/OpenDreamKit.github.io


# Custom vars
version:             0.3.0
repository:          OpenDreamKit/OpenDreamKit.github.io
bootstrap:           bootstrap-3.3.7-dist
tagfolder:           tag
menu:
    - title: 'The Project'
      folder: 'project'
    - title: 'The People'
      folder: 'people'
    - title: 'Events and Activities'
      folder: 'events_activities'

